trigger:
- main

pool:
  name: NetCorePublic-Pool
  queue: BuildPool.Windows.10.Amd64.VS2019.Open

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**\*.csproj'
- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\BuildResultAnalysisTest.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'