name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: pull-request
    attributes:
      label: Pull Request
      description: This is automatically filled from the issue that your opened this issue. Ignore if x
      value: This is the value
    validations:
      required: false
  - type: textarea
    id: builds-related
    attributes:
      label: Builds related
      description: Feel free to link the liks of the builds that are related to the issue so we can do further investigation
      placeholder: ALITZEL 
    validations:
      required: true
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: How you categorize the issue
      options:
        - Critital
        - Infrastructure
        - Repo
  - type: textarea
    id: error-message
    attributes:
      label: Error Message
      description: |
         Example: 
         {"errorMessage" : "The operation was canceled"}
      value: |
     
          "errorMessage" : ""
      
      render: json
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
