name: Report an infrastructure issue
description: Report an infrastructure issue causing build breaks across multiple builds
labels: ["First Responder", "Detected By - Customer", "Known Build Error"]
body:
  - type: markdown
    attributes:
      value: |
        This issue will be used to identify future build breaks with the same build error and will be displayed in [build analysis check]()
  - type: input
    id: build
    attributes:
      label: Build
      description: Enter link to failing build, Example. https://dev.azure.com/{organization}/{project}/_build/results?buildId={buildId} 
    validations:
      required: true
  - type: input
    id: build-leg
    attributes:
      label: Build leg reported
      description: Enter the name of the Stage/Job where the build break happened.
  - type: textarea
    id: error-message
    attributes:
      label: Error message
      description: This information is going to be fill in by the engineering services team. 
      value: |
         The engineering services team will fill in the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section).
         
         ```json
         {
            "ErrorMessage" : ""
         }
         ```
  - type: textarea
    id: additional-information
    attributes:
      label: Additional information about the issue reported
      description: Provide any details that could help with the investigation.
