name: Build Break - Report Repository Issue
description: File a repository issue causing build breaks
labels: ["bug", "triage"]
title: "[Build Break-Repository]: "
body:
  - type: markdown
    attributes:
      value: Thanks for reporting a repository build break.
  - type: input
    id: pull-request
    attributes:
      label: Pull Request
      description: If the issue was opened from the build analysis, this was automatically populated, feel free to update it.
  - type: input
    id: build
    attributes:
      label: Build
      description: If the issue was opened from the build analysis, this was automatically filled, feel free to update it with a link to any impacted build.
  - type: input
    id: build-error
    attributes:
      label: Build Error
      description: If the issue was opened from the build analysis, this was automatically populated, feel free to update it.
  - type: textarea
    id: error-message
    attributes:
      label: Error Message
      description: |
         This information should be filled by you or a repo owner. Using the [Known issues guidance](https://github.com/dotnet/core-eng/blob/f347870280b69d9224e48c948cd5a0ce0a334f8d/DevDocumentation/DevWorkflow/Design/Dev-Design-Infra-Known-Issues.md#investigation)
         The message should follow the format: { "errorMessage" : "The operation was canceled"}
      value: |
        {
         "ErrorMessage": "" 
        }
      render: json
  - type: textarea
    id: additional-information
    attributes:
      label: Additional information about the issue
  - type: checkboxes
    id: not-fr
    attributes:
     label: Repository issue
     description: | 
        By creating this issue, you are aware that this is not going to be triaged by FR, because this is an issue on the repository.  
        If this is not the case, please open an infrastructure issue 
     options:
        - label: This issue is only impacting the repository from which it was reported.
          required: true
