name: Report an infrastructure issue
description: Report an infrastructure issue causing build breaks across multiple builds
labels: ["First Responder", "Detected By - Customer", "Known Build Error"]
body:
  - type: markdown
    attributes:
      value: |
        This issue will be used to identify future build breaks with the same build error and will be displayed in [build analysis check]()
  - type: input
    id: build
    attributes:
      label: Build
      description: Enter link to failing build, Example. https://dev.azure.com/{organization}/{project}/_build/results?buildId={buildId} 
    validations:
      required: true
  - type: input
    id: build-leg
    attributes:
      label: Build leg reported
      description: Enter the name of the Stage/Job where the build break happened.
  - type: textarea
    id: error-message
    attributes:
      label: Action requiered
      description: This information is going to be fill in by the engineering services team. 
      value: |
        To triage this issue:
        - [ ] Open the failing build above and investigate
        - [ ] Add a comment explaining your findings 


        If this is an issue that is impacting causing build breaks across multiple builds and should get benefit from be listed on the build analysis check, follow the next steps:
        1. Add the label "Known Build Error"
        2. Edit this issue and add an error string in the Json below that can help us match this issue with future build breaks. You can use the [known issues documentation]()

         ```json
         {
            "ErrorMessage" : ""
         }
         ```
  - type: textarea
    id: additional-information
    attributes:
      label: Additional information about the issue reported
      description: Provide any details that could help with the investigation.
