name: Build Break - Report Infrastructure Issue
description: File an infrastructure issue causing build breaks to be investigated by FR
labels: ["First Responder", "Detected By - Customer", "Known Build Error"]
title: "[Build Break-Infrastructure]: "
body:
  - type: markdown
    attributes:
      value: Thanks for reporting an infrastructure build break for FR investigation.
  - type: input
    id: build
    attributes:
      label: Build
      description: If the issue was opened from the build analysis, this was automatically filled, feel free to update it with a link to any impacted build.
    validations:
      required: true
  - type: input
    id: build-leg-reported
    attributes:
      label: Build leg reported
      description: If the issue was opened from the build analysis, this was automatically filled, feel free to update it with any impacted leg.
  - type: textarea
    id: error-message
    attributes:
      label: Error message
      description: |
         This information is going to be filled in by FR (First Responders). Following the [known issues guidance](https://github.com/dotnet/core-eng/blob/f347870280b69d9224e48c948cd5a0ce0a334f8d/DevDocumentation/DevWorkflow/Design/Dev-Design-Infra-Known-Issues.md#investigation).
      value: |
       {
         "ErrorMessage": "" 
       }
      render: json
  - type: textarea
    id: additional-information
    attributes:
      label: Additional information about the issue reported
      description: Provide any details that could help with the investigation. Ex. links, logs, error.
  - type: checkboxes
    attributes:
      label: " "
      options: 
        - label: This issue should be investigated by @AlitzelMendez 

