name: Build Break - Infrastructure Report
description: File an infrastructure issue causing build breaks to be investigated by FR
labels: ["bug", "triage"]
title: "[Build Break]: "
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: Thanks for reporting an infraestructure build break for investigation. 
  - type: input
    id: pull-request
    attributes:
      label: Pull Request
      description: If the issue is open from the build analysis, this is automatically filled, feel free to update it. 
  - type: input
    id: build
    attributes:
      label: Build
      description: Feel free to link the liks of the builds that are related to the issue so we can do further investigation
  - type: input
    id: build-error
    attributes:
      label: Build Error
      description: Feel free to link the liks of the builds that are related to the issue so we can do further investigation
  - type: textarea
    id: error-message
    attributes:
      label: Error Message
      description: |
         This information should be filled by FR
      value: |
        {
         "ErrorMessage": "" 
        }
      render: json
  - type: textarea
    id: additional-information
    attributes:
      label: Additional information to investigate the Infrastructure build break
      description: Write any additional details that you consider important for the investigation

