name: Build Break - Infrastructure Report
description: File an infrastructure issue causing build breaks to be investigated by FR
labels: ["bug", "triage"]
title: "[Build Break]: "
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: Thanks for reporting an infrastructure build break for FR investigation. 
  - type: input
    id: pull-request
    attributes:
      label: Pull Request
      description: If the issue was opened from the build analysis, this was automatically populated, feel free to update it.
  - type: input
    id: build
    attributes:
      label: Build
      description: If the issue was opened from the build analysis, this was automatically filled, feel free to update it with a link to any impacted build.
    validations:
      required: true
  - type: input
    id: build-error
    attributes:
      label: Build Error
      description: If the issue was opened from the build analysis, this was automatically filled, feel free to update it.
  - type: textarea
    id: error-message
    attributes:
      label: Error Message
      description: |
         This information is going to be filled in by FR (First Responders). Following the [known issues guidance](https://github.com/dotnet/core-eng/blob/f347870280b69d9224e48c948cd5a0ce0a334f8d/DevDocumentation/DevWorkflow/Design/Dev-Design-Infra-Known-Issues.md#investigation)
      value: |
        {
         "ErrorMessage": "" 
        }
      render: json
  - type: textarea
    id: additional-information
    attributes:
      label: Additional information about the issue reported
      description: Provide any details that could help with the investigation

