name: Build Break - Report Repository Issue
description: File a repository issue causing build breaks
labels: ["Detected By - Customer", "Known Build Error"]
title: "[Build Break-Repository]: "
body:
  - type: markdown
    attributes:
      value: Thanks for reporting a repository build break.
  - type: input
    id: build
    attributes:
      label: Build
      description: If the issue was opened from the build analysis, this was automatically filled, feel free to update it with a link to any impacted build.
  - type: input
    id: build-leg-reported
    attributes:
      label: Build leg reported
      description: If the issue was opened from the build analysis, this was automatically populated, feel free to update it with any impacted leg.
  - type: textarea
    id: error-message
    attributes:
      label: Error Message
      description: |
         This information should be filled by you or a repo owner. Using the [Known issues guidance](https://github.com/dotnet/core-eng/blob/f347870280b69d9224e48c948cd5a0ce0a334f8d/DevDocumentation/DevWorkflow/Design/Dev-Design-Infra-Known-Issues.md#investigation)
         The message should follow the format: { "ErrorMessage" : "The operation was canceled"}
      value: |
        {
         "ErrorMessage": "" 
        }
      render: json
  - type: checkboxes
    id: not-fr
    attributes:
     label: Repository issue
     description: | 
        By creating this issue, you are aware that this is not going to be investigated by the engineering services team, because this is an issue on the repository.  
        If this is not the case, please open an infrastructure issue 
     options:
        - label: This issue is only impacting the repository from which it was reported.
          required: truename: Build Break - Report Repository Issue
description: File a repository issue causing build breaks
labels: ["Detected By - Customer", "Known Build Error"]
title: "[Build Break-Repository]: "
body:
  - type: markdown
    attributes:
      value: Thanks for reporting a repository build break.
  - type: input
    id: build
    attributes:
      label: Build
      description: If the issue was opened from the build analysis, this was automatically filled, feel free to update it with a link to any impacted build.
  - type: input
    id: build-leg-reported
    attributes:
      label: Build leg reported
      description: If the issue was opened from the build analysis, this was automatically populated, feel free to update it with any impacted leg.
  - type: textarea
    id: error-message
    attributes:
      label: Error Message
      description: |
         This information should be filled by you or a repo owner. Using the [Known issues guidance](https://github.com/dotnet/core-eng/blob/f347870280b69d9224e48c948cd5a0ce0a334f8d/DevDocumentation/DevWorkflow/Design/Dev-Design-Infra-Known-Issues.md#investigation)
         The message should follow the format: { "ErrorMessage" : "The operation was canceled"}
      value: |
        {
         "ErrorMessage": "" 
        }
      render: json
  - type: checkboxes
    id: not-fr
    attributes:
     label: Repository issue
     description: | 
        By creating this issue, you are aware that this is not going to be investigated by the engineering services team, because this is an issue on the repository.  
        If this is not the case, please open an infrastructure issue 
     options:
        - label: This issue is only impacting the repository from which it was reported.
          required: true
